# 開発環境用DBの接続情報を環境変数に設定します
version: '3'                                              # Docker Composeファイルのバージョンを指定します
  
services:                                                 # サービスの定義を開始します
  db:                                                     # "db"という名前のサービスを定義します
    image: postgres:14                                    # PostgreSQLのバージョン14のイメージを使用します
    container_name: postgres_pta                          # コンテナの名前を"postgres_pta"に設定します
    ports:
      - 5432:5432                                         # ホストのポート5432をコンテナのポート5432にマッピングします
    volumes:
      - db-store:/var/lib/postgresql/data                 # "db-store"ボリュームをコンテナのデータディレクトリにマウントします
    environment:
      POSTGRES_USER: 'user'                               # PostgreSQLのユーザー名を"user"に設定します
      POSTGRES_PASSWORD: 'postgres'                       # PostgreSQLのパスワードを"postgres"に設定します

  pgadmin4:                                               # "pgadmin4"という名前のサービスを定義します
    image: dpage/pgadmin4                                 # pgAdmin 4のイメージを使用します
    ports:
        - 8888:80                                         # ホストのポート8888をコンテナのポート80にマッピングします
    volumes:
        - pgadmin4_data:/var/lib/pgadmin                  # "pgadmin4_data"ボリュームをコンテナのデータディレクトリにマウントします
    environment:
        PGADMIN_DEFAULT_EMAIL: xxxxxxxxxx@gmail.com       # pgAdminのデフォルトメールアドレスを設定します
        PGADMIN_DEFAULT_PASSWORD: password                # pgAdminのデフォルトパスワードを設定します
    depends_on:
      - db                                                # "db"サービスに依存します
volumes:
  db-store:                                               # "db-store"という名前のボリュームを定義します
  pgadmin4_data:                                          # "pgadmin4_data"という名前のボリュームを定義します
